site_name: py_uds_demo
site_url: https://chaitu-ycr.github.io/py_uds_demo/
site_description: Learn and Practice UDS Protocol
site_author: chaitu-ycr

repo_name: chaitu-ycr/py_uds_demo
repo_url: https://github.com/chaitu-ycr/py_uds_demo
edit_uri: blob/main/docs/

nav:
  - Overview: index.md
  - Reference: reference_manual.md

plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            merge_init_into_class: true
            show_docstring_modules: false
  - include-markdown:
      recursive: true
  - search

theme:
  name: readthedocs
  features:
    - toc.integrate
    - search
