name: lint-and-test

on:
  push:
  workflow_dispatch:

jobs:
  lint-and-test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv build
          uv sync

      - name: Run pylint
        run: uv run pylint py_uds_demo

      - name: Run pytest
        run: uv run pytest

      - name: Run pytest with junitxml
        run: uv run pytest --junitxml=result.xml

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: result.xml
